//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Recursos_Humanos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empleados> empleadosSet { get; set; }
        public virtual DbSet<departamentos> departamentosSet { get; set; }
        public virtual DbSet<cargos> cargosSet { get; set; }
        public virtual DbSet<nominas> nominasSet { get; set; }
        public virtual DbSet<salida> salidaSet { get; set; }
        public virtual DbSet<permisos> permisosSet { get; set; }
        public virtual DbSet<licencias> licenciasSet { get; set; }
        public virtual DbSet<vacaciones> vacacionesSet { get; set; }
    }
}
