//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Recursos_Humanos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleados()
        {
            this.estatus = "Activo";
        }
    
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Remote("IsProductNameExist", "empleados", AdditionalFields = "Id",
               ErrorMessage = "Este codigo de empleado ya esta en uso")]
        public string codigoempleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string departamento { get; set; }
        public string cargo { get; set; }
        public string fechaingreso { get; set; }
        public int salario { get; set; }
        public string estatus { get; set; }

       
    }
}
