//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Recursos_Humanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacaciones
    {
        public int Id { get; set; }
        public string empleado { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
        public string correspondiente { get; set; }
        public string comentarios { get; set; }
    }
}
